name: Python tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pre-commit
      - name: Run pre-commit
        run: |
          pre-commit run --all-files
      - name: Lint draw-callback storage
        run: |
          python tools/check_draw_callback_storage.py
      - name: Run tests
        run: |
          pytest -q
